const pageModules = import.meta.glob([
  "../tools/*/index.html",
  "!../tools/_*/index.html",
]);

const preferredOrder = [
  "json-formatter",
  "timestamp-converter",
  "codec",
  "string-generator",
  "hosts-manager",
  "url-lab",
  "regex-lab",
  "text-diff",
  "number-base",
  "cron-expression",
  "ip-cidr",
  "color-lab",
  "image-process",
  "qr-code",
  "jwt-lab",
  "chmod-lab",
  "cert-lab",
  "curl-lab",
  "port-scan",
];

/** Localized title/description for known tools; unknown folders still appear by id. */
export const toolMeta = {
  "hosts-manager": {
    title: {
      en: "Hosts Manager",
      "zh-Hans": "Hosts 管理",
      "zh-Hant": "Hosts 管理",
      ja: "Hosts 管理",
      ko: "Hosts 관리",
      es: "Gestor de hosts",
      fr: "Gestionnaire Hosts",
      de: "Hosts-Manager",
      "pt-BR": "Gerenciador de hosts",
      ru: "Менеджер hosts",
    },
    description: {
      en: "View the system hosts file and switch mappings between environments",
      "zh-Hans": "查看系统 hosts，并在开发环境间切换映射",
      "zh-Hant": "檢視系統 hosts，並在開發環境間切換對應",
      ja: "システム hosts を確認し、環境ごとにマッピングを切り替え",
      ko: "시스템 hosts를 확인하고 환경별 매핑을 전환",
      es: "Consulta /etc/hosts y cambia mapeos entre entornos",
      fr: "Consultez /etc/hosts et basculez les mappings par environnement",
      de: "System-Hosts ansehen und Umgebungs-Mappings wechseln",
      "pt-BR": "Veja o hosts do sistema e alterne mapeamentos entre ambientes",
      ru: "Просмотр /etc/hosts и переключение окружений",
    },
  },
  "timestamp-converter": {
    title: {
      en: "Timestamp Converter",
      "zh-Hans": "时间戳转换",
      "zh-Hant": "時間戳轉換",
      ja: "タイムスタンプ変換",
      ko: "타임스탬프 변환",
      es: "Conversor de marcas de tiempo",
      fr: "Convertisseur d’horodatage",
      de: "Zeitstempel-Konverter",
      "pt-BR": "Conversor de timestamp",
      ru: "Конвертер временных меток",
    },
    description: {
      en: "Convert dates and Unix timestamps, with relative time offsets",
      "zh-Hans": "互转日期与 Unix 时间戳，并计算相对时间",
      "zh-Hant": "互轉日期與 Unix 時間戳，並計算相對時間",
      ja: "日付と Unix タイムスタンプを変換し、相対時間を計算",
      ko: "날짜와 Unix 타임스탬프를 변환하고 상대 시간을 계산",
      es: "Convierte fechas y marcas Unix y calcula tiempos relativos",
      fr: "Convertissez dates et horodatages Unix avec décalages relatifs",
      de: "Datum und Unix-Zeitstempel umrechnen und relativ verschieben",
      "pt-BR": "Converta datas e timestamps Unix com deslocamentos relativos",
      ru: "Преобразование дат и меток Unix с относительными смещениями",
    },
  },
  "json-formatter": {
    title: {
      en: "JSON Formatter",
      "zh-Hans": "JSON 格式化",
      "zh-Hant": "JSON 格式化",
      ja: "JSON フォーマッタ",
      ko: "JSON 포맷터",
      es: "Formateador JSON",
      fr: "Formateur JSON",
      de: "JSON-Formatierer",
      "pt-BR": "Formatador JSON",
      ru: "Форматирование JSON",
    },
    description: {
      en: "Format, minify, and query JSON with path expressions",
      "zh-Hans": "格式化、压缩，并用路径表达式查询 JSON",
      "zh-Hant": "格式化、壓縮，並用路徑運算式查詢 JSON",
      ja: "JSON の整形・圧縮・パス式クエリ",
      ko: "JSON 포맷·압축 및 경로 표현식 조회",
      es: "Formatea, minifica y consulta JSON con rutas",
      fr: "Formatez, minifiez et interrogez du JSON par chemin",
      de: "JSON formatieren, verkleinern und per Pfad abfragen",
      "pt-BR": "Formate, minifique e consulte JSON com caminhos",
      ru: "Форматирование, сжатие и запросы JSON по путям",
    },
  },
  codec: {
    title: {
      en: "Codec",
      "zh-Hans": "编解码",
      "zh-Hant": "編解碼",
      ja: "コーデック",
      ko: "코덱",
      es: "Códec",
      fr: "Codec",
      de: "Codec",
      "pt-BR": "Codec",
      ru: "Кодек",
    },
    description: {
      en: "Encode and decode Base64, Hex, URL, HTML, Unicode, Escape, and Hash",
      "zh-Hans": "编解码 Base64、Hex、URL、HTML、Unicode、转义与哈希",
      "zh-Hant": "編解碼 Base64、Hex、URL、HTML、Unicode、跳脫與雜湊",
      ja: "Base64・Hex・URL・HTML・Unicode・エスケープ・ハッシュ",
      ko: "Base64, Hex, URL, HTML, Unicode, 이스케이프, 해시",
      es: "Codifica y decodifica Base64, Hex, URL, HTML, Unicode y hash",
      fr: "Encodez et décodez Base64, Hex, URL, HTML, Unicode et hash",
      de: "Kodieren und dekodieren: Base64, Hex, URL, HTML, Unicode, Hash",
      "pt-BR": "Codifique e decodifique Base64, Hex, URL, HTML, Unicode e hash",
      ru: "Кодирование Base64, Hex, URL, HTML, Unicode, escape и хеш",
    },
  },
  "string-generator": {
    title: {
      en: "String Generator",
      "zh-Hans": "字符串生成",
      "zh-Hant": "字串產生",
      ja: "文字列ジェネレーター",
      ko: "문자열 생성기",
      es: "Generador de cadenas",
      fr: "Générateur de chaînes",
      de: "String-Generator",
      "pt-BR": "Gerador de strings",
      ru: "Генератор строк",
    },
    description: {
      en: "Generate UUIDs, random IDs, and strings locally",
      "zh-Hans": "本地生成 UUID、随机 ID 与字符串",
      "zh-Hant": "本機產生 UUID、隨機 ID 與字串",
      ja: "UUID・ランダム ID・文字列をローカル生成",
      ko: "UUID, 임의 ID, 문자열을 로컬에서 생성",
      es: "Genera UUID, ID aleatorios y cadenas en local",
      fr: "Générez UUID, ID aléatoires et chaînes localement",
      de: "UUIDs, Zufalls-IDs und Zeichenketten lokal erzeugen",
      "pt-BR": "Gere UUIDs, IDs aleatórios e strings localmente",
      ru: "Локально создавайте UUID, случайные ID и строки",
    },
  },
  "regex-lab": {
    title: {
      en: "Regex Lab",
      "zh-Hans": "正则实验室",
      "zh-Hant": "正則實驗室",
      ja: "正規表現ラボ",
      ko: "정규식 랩",
      es: "Laboratorio regex",
      fr: "Labo regex",
      de: "Regex-Labor",
      "pt-BR": "Lab de regex",
      ru: "Лаборатория regex",
    },
    description: {
      en: "Highlight matches, inspect capture groups, and try common replacements",
      "zh-Hans": "匹配高亮、分组捕获与常用替换",
      "zh-Hant": "符合高亮、分組擷取與常用取代",
      ja: "一致強調・キャプチャ・よく使う置換",
      ko: "일치 강조, 캡처 그룹, 자주 쓰는 치환",
      es: "Resalta coincidencias, grupos y sustituciones habituales",
      fr: "Surlignage, groupes de capture et remplacements courants",
      de: "Treffer hervorheben, Gruppen prüfen, Ersetzungen testen",
      "pt-BR": "Destaque matches, grupos e substituições comuns",
      ru: "Подсветка совпадений, группы и типичные замены",
    },
  },
  "text-diff": {
    title: {
      en: "Text Diff",
      "zh-Hans": "文本 Diff",
      "zh-Hant": "文字 Diff",
      ja: "テキスト Diff",
      ko: "텍스트 Diff",
      es: "Diff de texto",
      fr: "Diff de texte",
      de: "Text-Diff",
      "pt-BR": "Diff de texto",
      ru: "Diff текста",
    },
    description: {
      en: "Compare two texts side by side with line-level highlighting",
      "zh-Hans": "左右对比文本并高亮行级差异",
      "zh-Hant": "左右比對文字並高亮行級差異",
      ja: "左右比較と行単位の差分強調",
      ko: "좌우 비교와 행 단위 강조",
      es: "Compara textos en paralelo con resaltado por líneas",
      fr: "Comparez deux textes côte à côte, ligne par ligne",
      de: "Texte nebeneinander mit zeilenweiser Hervorhebung vergleichen",
      "pt-BR": "Compare textos lado a lado com destaque por linha",
      ru: "Сравнение двух текстов с подсветкой по строкам",
    },
  },
  "ip-cidr": {
    title: {
      en: "IP / CIDR",
      "zh-Hans": "IP / CIDR",
      "zh-Hant": "IP / CIDR",
      ja: "IP / CIDR",
      ko: "IP / CIDR",
      es: "IP / CIDR",
      fr: "IP / CIDR",
      de: "IP / CIDR",
      "pt-BR": "IP / CIDR",
      ru: "IP / CIDR",
    },
    description: {
      en: "Inspect IPv4 and IPv6 addresses or calculate IPv4 CIDR ranges locally",
      "zh-Hans": "本地查看 IPv4 / IPv6 地址或计算 IPv4 CIDR 范围",
      "zh-Hant": "本機檢視 IPv4 / IPv6 位址或計算 IPv4 CIDR 範圍",
      ja: "IPv4 / IPv6 の確認と IPv4 CIDR 範囲の計算",
      ko: "IPv4/IPv6 주소 확인 및 IPv4 CIDR 범위 계산",
      es: "Inspecciona IPv4/IPv6 o calcula rangos CIDR IPv4",
      fr: "Inspectez IPv4/IPv6 ou calculez les plages CIDR IPv4",
      de: "IPv4/IPv6 prüfen oder IPv4-CIDR-Bereiche berechnen",
      "pt-BR": "Inspecione IPv4/IPv6 ou calcule intervalos CIDR IPv4",
      ru: "Проверка IPv4/IPv6 и расчёт диапазонов IPv4 CIDR",
    },
  },
  "cron-expression": {
    title: {
      en: "Cron Expression",
      "zh-Hans": "Cron 表达式",
      "zh-Hant": "Cron 運算式",
      ja: "Cron 式",
      ko: "Cron 표현식",
      es: "Expresión cron",
      fr: "Expression cron",
      de: "Cron-Ausdruck",
      "pt-BR": "Expressão cron",
      ru: "Cron-выражение",
    },
    description: {
      en: "Build five-field cron schedules and preview upcoming runs",
      "zh-Hans": "编写五段 cron 并预览接下来的执行时间",
      "zh-Hant": "編寫五段 cron 並預覽接下來的執行時間",
      ja: "5 フィールド cron と次回実行の確認",
      ko: "5필드 cron 작성과 다음 실행 미리보기",
      es: "Crea cron de cinco campos y ve próximas ejecuciones",
      fr: "Créez des cron à cinq champs et voyez les prochaines exécutions",
      de: "Fünf-Feld-Cron erstellen und nächste Läufe prüfen",
      "pt-BR": "Crie cron de cinco campos e veja próximas execuções",
      ru: "Пятиполевой cron и ближайшие запуски",
    },
  },
  "color-lab": {
    title: {
      en: "Color Lab",
      "zh-Hans": "颜色实验室",
      "zh-Hant": "顏色實驗室",
      ja: "カラーラボ",
      ko: "색상 랩",
      es: "Laboratorio de color",
      fr: "Labo couleur",
      de: "Farblabor",
      "pt-BR": "Lab de cores",
      ru: "Цветовая лаборатория",
    },
    description: {
      en: "Convert HEX, RGB, HSL, and HSV with local contrast checks",
      "zh-Hans": "本地转换 HEX / RGB / HSL / HSV 并检查对比度",
      "zh-Hant": "本機轉換 HEX / RGB / HSL / HSV 並檢查對比度",
      ja: "HEX・RGB・HSL・HSV 変換とコントラスト確認",
      ko: "HEX, RGB, HSL, HSV 변환과 대비 확인",
      es: "Convierte HEX, RGB, HSL y HSV con contraste local",
      fr: "Convertissez HEX, RGB, HSL et HSV avec contraste local",
      de: "HEX, RGB, HSL und HSV lokal mit Kontrastprüfung",
      "pt-BR": "Converta HEX, RGB, HSL e HSV com contraste local",
      ru: "Конвертация HEX, RGB, HSL, HSV и проверка контраста",
    },
  },
  "qr-code": {
    title: {
      en: "QR Code",
      "zh-Hans": "二维码",
      "zh-Hant": "QR 碼",
      ja: "QR コード",
      ko: "QR 코드",
      es: "Código QR",
      fr: "Code QR",
      de: "QR-Code",
      "pt-BR": "Código QR",
      ru: "QR-код",
    },
    description: {
      en: "Generate QR codes from text or URLs locally",
      "zh-Hans": "本地从文本或 URL 生成二维码",
      "zh-Hant": "本機從文字或 URL 產生 QR 碼",
      ja: "テキストや URL から QR をローカル生成",
      ko: "텍스트나 URL로 QR을 로컬 생성",
      es: "Genera códigos QR desde texto o URL en local",
      fr: "Générez des QR à partir de texte ou d’URL en local",
      de: "QR-Codes lokal aus Text oder URLs erzeugen",
      "pt-BR": "Gere códigos QR a partir de texto ou URL localmente",
      ru: "Локально создавайте QR из текста или URL",
    },
  },
  "url-lab": {
    title: {
      en: "URL Lab",
      "zh-Hans": "URL 实验室",
      "zh-Hant": "URL 實驗室",
      ja: "URL ラボ",
      ko: "URL 랩",
      es: "Lab URL",
      fr: "Labo URL",
      de: "URL-Labor",
      "pt-BR": "Lab URL",
      ru: "URL-лаборатория",
    },
    description: {
      en: "Parse and rebuild URLs with query and hash editing",
      "zh-Hans": "解析与拼装 URL，编辑查询参数与哈希",
      "zh-Hant": "解析與組裝 URL，編輯查詢參數與雜湊",
      ja: "URL の解析・再構成とクエリ編集",
      ko: "URL 파싱·조립과 쿼리 편집",
      es: "Analiza y reconstruye URLs con query y hash",
      fr: "Analysez et reconstruisez des URL avec requête et hash",
      de: "URLs zerlegen und mit Query/Hash neu bauen",
      "pt-BR": "Analise e remonte URLs com query e hash",
      ru: "Разбор и сборка URL с query и hash",
    },
  },
  "number-base": {
    title: {
      en: "Unit Converter",
      "zh-Hans": "单位换算",
      "zh-Hant": "單位換算",
      ja: "単位変換",
      ko: "단위 변환",
      es: "Conversor de unidades",
      fr: "Convertisseur d’unités",
      de: "Einheitenrechner",
      "pt-BR": "Conversor de unidades",
      ru: "Конвертер единиц",
    },
    description: {
      en: "Convert bases, bytes, time, length, mass, temperature, and more locally",
      "zh-Hans": "本地换算进制、字节、时间、长度、质量、温度等",
      "zh-Hant": "本機換算進位、位元組、時間、長度、質量、溫度等",
      ja: "基数・バイト・時間・長さ・質量・温度などをローカル変換",
      ko: "진법, 바이트, 시간, 길이, 질량, 온도 등을 로컬 변환",
      es: "Convierte bases, bytes, tiempo, longitud, masa, temperatura y más",
      fr: "Convertissez bases, octets, temps, longueur, masse, température et plus",
      de: "Basen, Bytes, Zeit, Länge, Masse, Temperatur und mehr lokal umwandeln",
      "pt-BR": "Converta bases, bytes, tempo, comprimento, massa, temperatura e mais",
      ru: "Локальный перевод оснований, байтов, времени, длины, массы, температуры и др.",
    },
  },
  "image-process": {
    title: {
      en: "Image Tools",
      "zh-Hans": "图片处理",
      "zh-Hant": "圖片處理",
      ja: "画像ツール",
      ko: "이미지 도구",
      es: "Herramientas de imagen",
      fr: "Outils image",
      de: "Bildwerkzeuge",
      "pt-BR": "Ferramentas de imagem",
      ru: "Инструменты изображений",
    },
    description: {
      en: "Convert formats and control output by quality, target size, or dimensions",
      "zh-Hans": "转换格式，并按质量、目标大小或尺寸控制输出",
      "zh-Hant": "轉換格式，並依品質、目標大小或尺寸控制輸出",
      ja: "形式変換と品質・目標サイズ・寸法での出力制御",
      ko: "형식 변환과 품질·목표 용량·크기 출력 제어",
      es: "Convierte formatos y controla la salida por calidad, tamaño o dimensiones",
      fr: "Convertissez les formats et contrôlez la sortie par qualité, taille ou dimensions",
      de: "Formate konvertieren und Ausgabe per Qualität, Zielgröße oder Abmessungen steuern",
      "pt-BR": "Converta formatos e controle a saída por qualidade, tamanho ou dimensões",
      ru: "Конвертация форматов и управление выводом по качеству, размеру или габаритам",
    },
  },
  "jwt-lab": {
    title: {
      en: "JWT Lab",
      "zh-Hans": "JWT 查看",
      "zh-Hant": "JWT 檢視",
      ja: "JWT ラボ",
      ko: "JWT 랩",
      es: "JWT Lab",
      fr: "JWT Lab",
      de: "JWT Lab",
      "pt-BR": "JWT Lab",
      ru: "JWT Lab",
    },
    description: {
      en: "Decode JWT headers and payloads locally without uploading tokens",
      "zh-Hans": "本地解码 JWT，不上传 Token",
      "zh-Hant": "本機解碼 JWT，不上傳 Token",
      ja: "JWT をローカルでデコード（送信なし）",
      ko: "JWT를 로컬에서 디코딩 (업로드 없음)",
      es: "Decodifica JWT en local sin subir tokens",
      fr: "Décodez les JWT en local sans les envoyer",
      de: "JWT lokal dekodieren ohne Upload",
      "pt-BR": "Decodifique JWT localmente sem enviar tokens",
      ru: "Локально декодируйте JWT без отправки",
    },
  },
  "chmod-lab": {
    title: {
      en: "chmod Lab",
      "zh-Hans": "权限换算",
      "zh-Hant": "權限換算",
      ja: "chmod ラボ",
      ko: "chmod 랩",
      es: "chmod Lab",
      fr: "chmod Lab",
      de: "chmod Lab",
      "pt-BR": "chmod Lab",
      ru: "chmod Lab",
    },
    description: {
      en: "Convert Unix file modes between octal, symbolic, and permission bits",
      "zh-Hans": "本地换算 Unix 文件权限（八进制 / 符号 / 权限位）",
      "zh-Hant": "本機換算 Unix 檔案權限（八進位／符號／權限位）",
      ja: "Unix 権限を 8 進・記号・ビットで変換",
      ko: "Unix 권한을 8진수·기호·비트로 변환",
      es: "Convierte modos Unix entre octal, simbólico y bits",
      fr: "Convertissez les modes Unix (octal, symbolique, bits)",
      de: "Unix-Modi zwischen oktal, symbolisch und Bits umwandeln",
      "pt-BR": "Converta modos Unix entre octal, simbólico e bits",
      ru: "Перевод Unix-прав между восьмеричным, символьным видом и битами",
    },
  },
  "cert-lab": {
    title: {
      en: "Certificate Lab",
      "zh-Hans": "证书查看",
      "zh-Hant": "憑證檢視",
      ja: "証明書ラボ",
      ko: "인증서 랩",
      es: "Certificate Lab",
      fr: "Certificate Lab",
      de: "Certificate Lab",
      "pt-BR": "Certificate Lab",
      ru: "Certificate Lab",
    },
    description: {
      en: "Inspect PEM certificates, validity, fingerprints, and SANs locally",
      "zh-Hans": "本地查看 PEM 证书、有效期、指纹与 SAN",
      "zh-Hant": "本機檢視 PEM 憑證、有效期、指紋與 SAN",
      ja: "PEM 証明書・有効期限・指紋・SAN をローカル確認",
      ko: "PEM 인증서·유효기간·지문·SAN을 로컬에서 확인",
      es: "Inspecciona certificados PEM, validez, huellas y SAN en local",
      fr: "Inspectez certificats PEM, validité, empreintes et SAN en local",
      de: "PEM-Zertifikate, Gültigkeit, Fingerprints und SANs lokal prüfen",
      "pt-BR": "Inspecione certificados PEM, validade, fingerprints e SAN localmente",
      ru: "Локальный разбор PEM-сертификатов, сроков, отпечатков и SAN",
    },
  },
  "curl-lab": {
    title: {
      en: "cURL Lab",
      "zh-Hans": "cURL 实验室",
      "zh-Hant": "cURL 實驗室",
      ja: "cURL ラボ",
      ko: "cURL 랩",
      es: "cURL Lab",
      fr: "cURL Lab",
      de: "cURL Lab",
      "pt-BR": "cURL Lab",
      ru: "cURL Lab",
    },
    description: {
      en: "Visually edit HTTP requests and convert to or from cURL",
      "zh-Hans": "可视化编辑 HTTP 请求，与 cURL 互相转换",
      "zh-Hant": "視覺化編輯 HTTP 請求，與 cURL 互相轉換",
      ja: "HTTP リクエストを可視化編集し cURL と相互変換",
      ko: "HTTP 요청을 시각적으로 편집하고 cURL과 상호 변환",
      es: "Edita peticiones HTTP visualmente y convierte desde/hacia cURL",
      fr: "Éditez des requêtes HTTP visuellement et convertissez depuis/vers cURL",
      de: "HTTP-Requests visuell bearbeiten und von/nach cURL konvertieren",
      "pt-BR": "Edite requisições HTTP visualmente e converta de/para cURL",
      ru: "Визуально редактируйте HTTP-запросы и конвертируйте в/из cURL",
    },
  },
  "port-scan": {
    title: {
      en: "Port Scanner",
      "zh-Hans": "端口扫描",
      "zh-Hant": "連接埠掃描",
      ja: "ポートスキャナー",
      ko: "포트 스캐너",
      es: "Escáner de puertos",
      fr: "Scanner de ports",
      de: "Portscanner",
      "pt-BR": "Scanner de portas",
      ru: "Сканер портов",
    },
    description: {
      en: "Scan any TCP port or range with progress and open-port results",
      "zh-Hans": "扫描任意 TCP 端口或范围，显示进度与开放端口结果",
      "zh-Hant": "掃描任意 TCP 連接埠或範圍，顯示進度與開放連接埠結果",
      ja: "任意の TCP ポート/範囲を進捗付きでスキャンし開放ポートを表示",
      ko: "모든 TCP 포트나 범위를 진행률과 열린 포트 결과로 스캔",
      es: "Escanea cualquier puerto o rango TCP con progreso y resultados abiertos",
      fr: "Scannez tout port ou plage TCP avec progression et ports ouverts",
      de: "Beliebige TCP-Ports oder Bereiche mit Fortschritt und offenen Ports scannen",
      "pt-BR": "Escaneie qualquer porta ou intervalo TCP com progresso e portas abertas",
      ru: "Сканируйте любые TCP-порты или диапазоны с прогрессом и открытыми портами",
    },
  },
};

export function discoverToolIds() {
  return Object.keys(pageModules)
    .map((path) => path.match(/\/tools\/([^/]+)\//)?.[1])
    .filter((id) => id && !id.startsWith("_"))
    .sort((left, right) => {
      const leftRank = preferredOrder.indexOf(left);
      const rightRank = preferredOrder.indexOf(right);
      if (leftRank === -1 && rightRank === -1) return left.localeCompare(right);
      if (leftRank === -1) return 1;
      if (rightRank === -1) return -1;
      return leftRank - rightRank;
    });
}

function pickLocale(map, locale) {
  if (!map) return "";
  return map[locale] || map.en || Object.values(map)[0] || "";
}

export function listTools(locale = "en") {
  return discoverToolIds().map((id) => {
    const meta = toolMeta[id];
    return {
      id,
      title: pickLocale(meta?.title, locale) || id,
      description: pickLocale(meta?.description, locale),
      href: `./tools/${id}/`,
    };
  });
}
